### ISSUE TITLE
e2fsprogs 1.46.0 build fails

### ISSUE THREAD

**Issue by aabacchus** [kiss-community/repo#10]
Hi @git-bruh 
I've just tried to update e2fsprogs several times and it's failing every time:
```
        LD e2fsck
/usr/bin/ld: rehash.o: in function `e2fsck_rehash_dir':
rehash.c:(.text+0xebd): undefined reference to `qsort_r'
/usr/bin/ld: rehash.c:(.text+0x135c): undefined reference to `qsort_r'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:453: e2fsck] Error 1
make[2]: Leaving directory '/tmp/build-383859/e2fsprogs/e2fsck'
make[1]: *** [Makefile:443: all-progs-recursive] Error 1
make[1]: Leaving directory '/tmp/build-383859/e2fsprogs'
make: *** [Makefile:371: all] Error 2
-> e2fsprogs Build failed
```

**Comment by kyx0r** [comment]
Hmm this is glibc specific function which musl does not implement. I have run into some other project that used this qsort_r. You have to write a replacement, basically +one pretty big and nasty patch if there is no other way to disable it.

**Comment by git-bruh** [comment]
https://github.com/kiss-community/repo-community/issues/84#issuecomment-775647150
