### ISSUE TITLE
drop gnupg1

### ISSUE THREAD

**Issue by illiliti** [kiss-community/repo#105]
It is solely present here for commit signing/verification. Instead, let's use ssh-based signing because it is safer and less error-prone.

**Comment by ioraff** [comment]
> it is safer and less error-prone

how so?

**Comment by illiliti** [comment]
gnupg1 has been deprecated in favor of more bloated gnupg2. it is no longer maintained, that's why openssh method is more safer.
gnupg1 is known to be unreliable due to constant errors for unknown cause:
https://github.com/kisslinux/repo/issues/141
https://github.com/kisslinux/repo/issues/351

These issues still show up by this day.
