### ISSUE TITLE
peg git packages to known good commit

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo#109]
- [ ] mpv

**Comment by illiliti** [comment]
why?

**Comment by git-bruh** [comment]
A bad segfault causing commit could accidentally be pushed or an extra dep could be added which would cause the build to fail

**Comment by dilyn-corner** [comment]
> why?

It's bad for reproducible builds and makes maintaining any given git package a perpetual chore.

It seems sane to have packages in repositories only if they are in a known-working state.

**Comment by illiliti** [comment]
Not sure if this idea would be a sane choice for vim. See b46d9cf089f0bc16498ad45a677c0ddf0adb64c1

**Comment by dilyn-corner** [comment]
Yeah, I think vim is just insane in this instance...

Sep 21, 2022, 8:59 PM by ***@***.***:
