### ISSUE TITLE
libelf build fail

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#11]
```
checking whether gcc accepts -Wnull-dereference... yes
checking whether gcc accepts -Wimplicit-fallthrough... yes
checking for library containing argp_parse... no
configure: error: in `/root/.cache/kiss/proc/2371/build/libelf':
configure: error: failed to find argp_parse
See `config.log' for more details
-> libelf Build failed
```

Looks like the no argp_parse option does not work anymore.

**Comment by kyx0r** [comment]
@git-bruh How does it work on your end?

**Comment by git-bruh** [comment]
Apologies, i had only tested this package on glibc. Looks like they changed `configure` a bit, and added checks for some other stuff that musl doesn't have either, trying to bypass checks leads to build failure due to musl not having an `error.h` :
```
checking for library containing argp_parse... no
checking for library containing fts_close... no
checking for library containing _obstack_free... no
```
I will revert this package to 0.182 for now

**Comment by git-bruh** [comment]
turns out i was testing the build in a manually extracted tarball and hence did not have `files/error.h` lol, bypassing the checks worked fine. Stole the proper `sed` calls from carbslinux and updated the package
