### ISSUE TITLE
Dead links to https://git.sr.ht/ in packages

### ISSUE THREAD

**Issue by camthehaxman** [kiss-community/repo#112]
I decided to give KISS Linux a try in a VM. A few of the packages in this repo (scdoc, b3sum, grim, wlsunset, wayclip, and libseat) fetch their sources from a https://git.sr.ht/ url. However, I cannot access that domain at all, on my host machine, through a web browser, or anything. b3sum is the most critical one, since the kiss package manager depends on it.

**Comment by sewnie** [comment]
sourcehut is currently experiencing an outage...

https://status.sr.ht/

**Comment by camthehaxman** [comment]
Looks like it was a temporary outage. It's working now.
