### ISSUE TITLE
ncurses -> netbsd-curses ?

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo#13]
Not sure if anyone else is interested in this change, 10-15 packages from community will need to be tested and a few in main repo

https://github.com/sabotage-linux/netbsd-curses

**Comment by dilyn-corner** [comment]
Is there a good reason to not simply relegate this to `community`?

**Comment by git-bruh** [comment]
The `depends` file of each package would have to be updated to use `netbsd-curses`, you'll need to fork every package to use this instead of `ncurses` so it can't be moved to community.

Or did you mean moving the issue to `community` ?

**Comment by dilyn-corner** [comment]
I mean why wouldn't you simply add `netbsd-curses` to community like we put `{s,u}base, nawk, coreutils` in community? 
Moreso I mean what's the reason we would replace `ncurses` by `netbsd-curses`? What's the good, motivating reason to do it?

**Comment by git-bruh** [comment]
ah, I felt that `netbsd-curses` is more suitable for KISS than `ncurses` (`kiss size netbsd-curses: 3MB	total`, `kiss size ncurses: 17MB	total`), and the `depends` file is the issue with putting it in community. Nothing has a hard dependency on what base utilities you use so this is not the issue with `nawk` etc.

**Comment by git-bruh** [comment]
Actually, If someone wants to use `netbsd-curses` then they can just rename their package to `ncurses` which will make this a non-issue.

**Comment by dilyn-corner** [comment]
The size benefits are fine (great, even), but I'm not sure how one would build alsa-mixer with `netbsd-curses`, so you'd have to adapt `alsa-utils`. Additionally, `tic` won't work in the way many terminal emulators would expect; the most prominent example which comes to mind is `foot` (see [this](https://freenode.logbot.info/foot-terminal/20210202#c6758776)). I'm not sure what other terminal emulators are effected by this, but I'd imagine it's a nonzero number. 
If `st` builds with `netbsd-curses` with no issues (it should) and we're fine with adding --disable-alsamixer to `alsa-utils`, then I guess the switch is fine. The build files for community packages would have to be checked (like `htop` will not build without adjustment) but I can't think of any other program in the core repo which would have issues.

**Comment by git-bruh** [comment]
Looks like the issue with `foot` is present with `alacritty` aswell, and `alsamixer` is probably important for a lot of people. I now think that packaging `netbsd-curses` as `ncurses` would be the better approach if someone wants to swap out `ncurses`, I'll still try building all the packages with `netbsd-curses` to see if it would be feasible in main repos.

**Comment by git-bruh** [comment]
Some packages will need in community like `lynx` will need modifications from the README in the linked repo + stuff like `llvm` links to `ncurses` if available, we don't want to force everyone to rebuild such fat packages. There might be some other weirdness that might occur in some packages even if they build.
