### ISSUE TITLE
wget: https/ssl fails

### ISSUE THREAD

**Issue by ominitay** [kiss-community/repo#15]
Error returned is `wget: error getting response: Connection reset by peer`, but it works fine if run with the option `--no-check-certificate`

**Comment by git-bruh** [comment]
https://github.com/mirror/busybox/commit/fc2ce04a38ebfb03f9aeff205979786839cd5a7c is the cause, will investigate further, might be due to `libressl`.

**Comment by git-bruh** [comment]
It's because of  [this](https://github.com/mirror/busybox/blob/master/networking/wget.c#L708) line. `libressl` does not have the `-verify_hostname`/`-verify_ip` flag available:

```
-> openssl s_client -quiet -connect duckduckgo.com:443 -servername duckduckgo.com -verify 100 -verify_return_error -verify_hostname duckduckgo.com

verify depth is 100
unknown option -verify_hostname
usage: s_client [-4 | -6] [-alpn protocols] [-bugs] [-CAfile file]...
```

@cemkeylan, have you encountered this on carbs ?

**Comment by cemkeylan** [comment]
On Carbs, we don't have ssl verification for busybox wget enabled, because we use bearssl, though I was planning to patch it to use bearssl. I see busybox's wget as the "if all else fails" option, and it already warns the user that the ssl verification is disabled, so I never bumped into such an issue.

**Comment by git-bruh** [comment]
Hmm, so we can either revert the commit which fixed certificate verification or drop `CONFIG_FEATURE_WGET_OPENSSL=y`, both will lead to the verification being broken. For now atleast, i am just removing that option from `.config` and bumping release. Now `wget` will say `wget: note: TLS certificate validation not implemented`, people should use `curl` instead.

**Comment by cemkeylan** [comment]
Well, it is quite easy to patch out, so this should work with libressl. 
[libressl.patch.txt](https://github.com/kiss-community/repo-main/files/5994518/libressl.patch.txt)

By it should, I mean, I tried it with libressl and it works.

**Comment by git-bruh** [comment]
Yes @cemkeylan, but is this actually effective in verifying the certificate stuff ? Because the linked commit "fixes" the openssl flags, so maybe it was silently "failing" to verify earlier due to missing flags ?

**Comment by cemkeylan** [comment]
It is effective for verification on most cases. Without the `-verify_hostname` bit, `openssl` will check whether the certificate is valid, has a trusted certificate authority, not self-singed, not revoked, and not expired. The `verify_hostname` bit also adds the check to verify that the hostname and DNS records match. This is also an important verification, though.

**Comment by git-bruh** [comment]
Thanks, I'll add the patch then.
