### ISSUE TITLE
kiss: check if directory exists during update

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#19]
Hello @git-bruh and @dilyn-corner I've got a rather philosophical issue here. 

But first, i'd like to point out that on github the kiss package manager repository does not have a issues page like this repo-main
repository which is why I am writing it here. And yes I am too lazy to go onto IRC, so deal with it.

I have some repos paths being set to appended to KISS_PATH here.
https://github.com/kyx0r/klec/blob/685c860892ae81c3e009576ce36bb8c633d2e9b5/dotfiles/.profile#L6

As you can see, I am forced to check for every directory because if I don't when I run ```kiss update``` I get error message like this one:
```/usr/bin/kiss: cd: line 1307: can't cd to /root/kiss/gcommunity/community: No such file or directory```

The problem is that I use my configs on many different machines and not every machine has the same repos and requirements. And this error is not handled by the package manager which causes the update to fail. The problem can be solved by simply adding a check inside kiss on the return error code of the cd command. 

I hope it's not too big of an ask to add a check + continue in kiss so that I don't have to keep adding the monstrocity of if statements in my .profile . I might as well be beneficial to you also. But again you have to sacrifice 2 lines of code for that, which may or may not surpass the said minimalism standard.

**Comment by dilyn-corner** [comment]
I can take a peak at having `kiss` not exit when it fails to update any given repository in `KISS_PATH`, and find a nonintrusive way of notifying users their repositories aren't where they might think they are. 

Thanks for letting me know that issues can't be opened at the package manager repo; I've enabled them there and for init.

**Comment by dilyn-corner** [comment]
Resolved & released in https://github.com/kiss-community/kiss/commit/152bb477a34997800ad7933620691e8d83523055
