### ISSUE TITLE
ffmpeg: drop static libs

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo#24]
I don't think anything statically links ffmpeg, so static libs waste 100+ MB of space:

```
2MB     /usr/lib/libswscale.a
508KB   /usr/lib/libswresample.a
288KB   /usr/lib/libpostproc.a
2MB     /usr/lib/libavutil.a
19MB    /usr/lib/libavformat.a
18MB    /usr/lib/libavfilter.a
736KB   /usr/lib/libavdevice.a
65MB    /usr/lib/libavcodec.a

132MB   total (full package, including shared libs)
```

**Comment by dilyn-corner** [comment]
This is probably a good idea(tm) without actually thinking too carefully on it. Assuming it doesn't break things (I see no good reason why it shouldn't), this can be done - we already do it with several other packages anyways, and their static libs are far smaller.
