### ISSUE TITLE
busybox: powertop: no stats available

### ISSUE THREAD

**Issue by jslick** [kiss-community/repo#25]
When running busybox powertop (as root), I see `powertop: no stats available; run as root or enable the timer_stats module`.  Looking at powertop.c, it looks like it uses /proc/timer_stats , but looking at `man 5 proc` (http://manpages.ubuntu.com/manpages/bionic/man5/proc.5.html), it looks like this was removed in linux 4.10.

I personally am not excited about a busybox version of powertop; I would propose disabling `CONFIG_POWERTOP` in the busybox config.

**Comment by dilyn-corner** [comment]
Can do!
