### ISSUE TITLE
Replacing udev guide is outdated

### ISSUE THREAD

**Issue by illiliti** [kiss-community/repo#26]
https://github.com/kiss-community/repo-main/blob/88cac66cb3a3f37ee74076ee61874d2c5d7b5dea/extra/libinput/build#L19

This option is deprecated and no longer needed.

As well as https://k1sslinux.org/wiki/dev/replacing-udev outdated too.

**Comment by dilyn-corner** [comment]
Thanks for the reminder on the `libinput` build.

What part of the wiki page is outdated?

**Comment by illiliti** [comment]
The whole page is outdated because it describes old way to rip out udev from the system, which is rather confusing than helpful. I think that we should rewrite this page in favor of libudev-zero or drop it entirely to stop confusing newcomers.

**Comment by dilyn-corner** [comment]
That's a fair criticism. 

Feel free to write something up, or provide some suggestions if you rather not. I'll try to touch on this soon(tm). 

Mar 13, 2021, 12:17 AM by ***@***.***:

**Comment by dilyn-corner** [comment]
This is being worked on here https://github.com/kiss-community/wiki/pull/10

**Comment by dilyn-corner** [comment]
It was merged! :)
