### ISSUE TITLE
xfsprogs: meson is dependency

### ISSUE THREAD

**Issue by ghost** [kiss-community/repo#27]
Trying to build `xfsprogs` without `meson` results in an error of `meson` isn't found

**Comment by ghost** [comment]
also, sorry if this is intentional or if i did something wrong, new to this distro

**Comment by illiliti** [comment]
Looks like @git-bruh forgot to add `meson` to depends file in this commit https://github.com/kiss-community/repo-main/commit/4ee742a1aeef19de11f9b4fe1551f21227afe1e7

**Comment by dilyn-corner** [comment]
ezclap
