### ISSUE TITLE
Loading kernel modules confusion

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#28]
I have some garbage drivers that need to be compiled as a module, otherwise kernel is not able to find the right firmware. I have a script that loads all the modules like so:

```
var=$(cat /lib/modules/5.11.0_1/modules.order)
for p in $var
do
        modprobe $(basename "$p")
done
```

The problem is if this is put into /etc/rc.conf this script will also run when doing poweroff, which isn't right. (But it does not cause problems usually) If I put this into /etc/rc.d/mod.boot instead the problem of being run on anything but boot will be solved, however the device manager will start before the kernel modules are loaded, which will cause for example sound to not work, or rather be muted, since device manager did not find any sound cards at boot. Is there any better way to handle this crap?

**Comment by kyx0r** [comment]
And also does the kernel option of building in firmware into it ever work? I have tried to embed the blobs I need, it worked, but it always fails to find firmware at boot, even though I have it compiled in. It makes no sense. I tried embeding blobs for gpu, realtek chip, and intel wifi, but it never works, snd kernel prints error of unable to load firmaware even if names %100 match. Also, all the drives were compiled into the kernel, not as a module.

**Comment by kyx0r** [comment]
ALSO: my drandma said she does not like this operating system. My dreams for year of linux desktop 2021 were ruined.

**Comment by illiliti** [comment]
What device manager do you use?
How did you compile modules and embed firmware?

Please provide more useful info and logs :+1:

**Comment by kyx0r** [comment]
>What device manager do you use?

Well, depends on the machine. I may be using udevd or mdev or nothing at all and just hardcode all the /dev/event*, doesn't matter. You guys start the device manager as a service? I don't cause I don't really need services to be honest. Unless I am setting up a public vps, that I would log into once a month. My rigs mine crypto and miner can restart itself anyways. It's also kinda bloat, if I need device manager for hotplug I can run it myself 'udevd -d' when I need it. The device manager is only run once here https://github.com/kiss-community/init/blob/master/lib/init/rc.boot#L36 and then it exits at the bottom of that file. That's why if you load the modules in /etc/rc.conf settings like sound, work because the realtek driver is already loaded and one of those commands actually works right after:
```
        udevd -d
        udevadm trigger -c add -t subsystems
        udevadm trigger -c add -t devices
        udevadm settle
```

but if modules are loaded in /etc/rc.d/mod.boot instead, those udev commands above would be run without driver loaded yet. 

>How did you compile modules and embed firmware?

Eh, I did mention that when I embed firmware I compile everything into the kernel; not a module. But it never works, that's why it makes no sense, the kernel should be self contained without any need to check into filesystem, but it seems like it's not possible to do? Does anybody here run their kernel as one single standalone vmlinuz executable ? 

>Please provide more useful info and logs +1

Nothing really to show yet, I want to get some feedback from the rest of the users to see how they actually handle this problem, and what might be the best way to configure the system. As of right now everythings works fine for me, for example if I modprobe from the /etc/rc.d/mod.boot I can work around the sound being muted by running some amixer commands directly, but I know that I technically don't have to do that if the driver is loaded first and udevd does it's thing.

**Comment by sdsddsd1** [comment]
I think your kernel .config would clearify the "embedding driver does not work".

**Comment by dilyn-corner** [comment]
Building firmwares into the kernel works just fine; I do it for my microcde and used to do it for my webcam. 

All firmware files should be specified on a space-separated list with paths relative to what is set for `CONFIG_EXTRA_FIRMWARE_DIR`. The [relevant lines](https://github.com/dilyn-corner/KISS-me/blob/6d4ef0959406f2d6ec2723bd5d1f0db88d82d97a/gpl/linux/files/.config#L1107) of my `.config` for example.

You might find a few pages of the [kernel's documentation](https://www.kernel.org/doc/html/v4.14/driver-api/firmware/built-in-fw.html) useful, but probably not exhaustive. 

[Here](https://unix.stackexchange.com/questions/261725/how-does-linux-load-firmeware-for-built-in-driver-modules) is a short-and-sweet StackExchange QA that also explains it a little bit. 

My only question is, IF putting the relevant lines in `/etc/rc.conf` has the desired effect (but a undesireable and ultimately nonfatal sideeffect), what is the actual problem? 

If you actually want to avoid the undesired sideeffect you could probably [add a check of some kind](https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced).

**Comment by kyx0r** [comment]
Alright, thanks for the input everyone. I'll close this issue for now because I am not sure when will I have time to reconfigure the kernel and mess around with these things again. But everything works anyway I am happy as is.
