### ISSUE TITLE
kiss: outdated tarball link

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#29]
On the website and in kiss help install the link is:

$ url=https://github.com/kiss-community/repo/releases/download/2021.3-1

but that isn't right. when I download it and extract every folder is empty and symlinks are broken. 

Make sure to update those things when new release, also delete the broken 3-1 release as there is no point in keeping it. 
@dilyn-corner

**Comment by dilyn-corner** [comment]
I've updated the website page, thanks. 

We should immortalize my mistakes tho :v
