### ISSUE TITLE
Update gcc

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#33]
It's been 9 month for gcc, and I am tired of compiler bugs at different optimization levels. Maybe it's time to update it because it has probably already got a lot of bugs fixed hopefully.

**Comment by dilyn-corner** [comment]
`gcc` has an update? 

I don't think the repositories should update to git releases for such important pieces as the toolchain. 

Apr 4, 2021, 5:51 PM by ***@***.***:

**Comment by kyx0r** [comment]
Yes, but would it be possible to add an alternative gcc-git package in community repo? Also i hope 10.3 comes out soon, maybe few more month's. It's just been frustrating cause I ran into some -O0 optimization bugs today and wasted a lot of time debugging my applications trying to fugure out what was wrong, but it was a compiler bug cause any other compiler/optimization level works just fine.

**Comment by dilyn-corner** [comment]
You can definitely submit the git version of `gcc` to community! A few people might appreciate having the latest. 

Apr 4, 2021, 10:32 PM by ***@***.***:

**Comment by acheam0** [comment]
https://github.com/kiss-community/repo-main/commit/89dd85bceba833d8a45507f43dc19606504d6cd7
