### ISSUE TITLE
Does the mailing list work? 

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#37]
Hi finally I was able to get caught up on all the kiss news this month, I was trying to subscribe myself to the list but I get no confimation email from the server. I emailed dev+subscribe@k1sslinux.org directly and dev@k1sslinux.org with the keywords.

**Comment by dilyn-corner** [comment]
It does, I think your 'dev+' got stripped from your first email.

**Comment by kyx0r** [comment]
I tried like this: 

To:dev@k1sslinux.org
Subject:
Body:dev+subscribe@k1sslinux.org

To:dev+subscribe@k1sslinux.org
Subject:dev+subscribe@k1sslinux.org
Body:dev+subscribe@k1sslinux.org

To:dev+subscribe@k1sslinux.org
Subject:
Body:

What's the right way to do this? I haven't done this in ages ...

**Comment by dilyn-corner** [comment]
it should simply be an email with *any* subject & body to:
dev+subscribe@k1sslinux.org
Looking at the logs, it looks like you sent one and it went the right way, and you should've gotten a response almost instantly. Check spam, though gmail hasn't been doing that... 

I can always just manually add your name to the subscription list if you can't find it. 
Uncertain what the problem might be, tbh.

**Comment by kyx0r** [comment]
Yeah, I just got a confirmation email, it just took 10 minutes for it to go through... Damn are imap/smtp so slow? I replied now just gotta wait 10 more minutes probably for it to confirm.

**Comment by dilyn-corner** [comment]
for some people it takes a long time to come in. With Gmail, there's a noticeable lag between hitting send and when the email actually shows up at the server - this is, I believe, Gmail's fault. When the server gets an email, the turn-around on a response is basically <2 seconds (per the logs, you got a response very quickly). Why Gmail held up a legitimate email for an arbitrary amount of time, I do not know - but there was no problem on my end :v
