### ISSUE TITLE
cmake: checksum mismatch

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo#41]
```
-> Resolving dependencies
-> Building: cmake
-> cmake Checking repository files
-> Checking for pre-built dependencies
-> cmake Downloading sources
-> cmake Found cached source 'cmake-3.20.2.tar.gz'
-> cmake Found local relative source 'patches/cmake-no-execinfo.patch'
-> cmake Checksum mismatch
ERROR Checksum mismatch with: cmake
```

Let me know if more info required.

**Comment by dilyn-corner** [comment]
Have you tried deleting the cached source?

**Comment by kyx0r** [comment]
Damn you're right. How does this even happen? The filename did not change but the package was updated so it was trying to use the old cache. I never had this problem before, I guess must experience this once to know better.

**Comment by dilyn-corner** [comment]
You might've previously cancelled the update while the source was downloading and `kiss` didn't clean up after itself when you did. There was a recent commit https://github.com/kiss-community/kiss/commit/edfb25aa2da44076dcb35b19f8e6cfddd5a66dfa that changes trap behavior to avoid this that will be in a new release.

**Comment by kyx0r** [comment]
Ok thanks for help!
