### ISSUE TITLE
xinit uses non portable grep options

### ISSUE THREAD

**Issue by TAAPArthur** [kiss-community/repo#42]
xinit's `startx` uses non-portable grep flags (-o) on line 109
So proposing we change it from 
```
tty_num=$(echo "$tty" | grep -oE '[0-9]+$')
```
to
```
tty_num=$(tty | cut -c9)
```
Which could be done via 
```
sed -i "s/tty_num=.*/tty_num=\$(tty | cut -c9)/g" startx.cpp
```

**Comment by dilyn-corner** [comment]
Have you suggested this to them (on [gitlab](https://gitlab.freedesktop.org/xorg/app/xinit) or the [mailing list](https://lists.x.org/mailman/listinfo/xorg-devel))? They seemed at least semi-interested in portability, based on the comments on [this](https://gitlab.freedesktop.org/xorg/app/xinit/-/issues/6) (ancient) issue. 

Depending on what they say we can see! :) If they don't want it, we can always just do it ourselves; but upstreaming these sorts of things is part of our goals.

**Comment by TAAPArthur** [comment]
I can try. Took the last suggestion from that 6yr old issue and submitted a [PR](https://gitlab.freedesktop.org/xorg/app/xinit/-/merge_requests/5).

Probably scarred from the less than ideal experience with trying push my patch to meson to get it to work with generic compilers... I do agree it's better to get things upstream if possible.

**Comment by TAAPArthur** [comment]
@dilyn-corner It has been merged upstream.

**Comment by dilyn-corner** [comment]
You love to see it!
