### ISSUE TITLE
Notification of new releases

### ISSUE THREAD

**Issue by Vouivre** [kiss-community/repo#5]
I hope we will have some news from @dylanaraps soon, but I expect it won't happens before many weeks. 

What do you think about adding some repo's to repology ? 

I just realized I won't get any notification for new releases of softwares as soon as a software is outdated on https://github.com/kisslinux/community. It's the reason why I created a PR with an outdated software (PR https://github.com/kiss-community/repo-community/pull/15).  So I have to think to a solution to get notification of new releases without the notification from repology for packages on  https://github.com/kisslinux/community.

**Comment by sdsddsd1** [comment]
You can use `kiss-outdated /path/to/repo` to check for new releases somewhat reliable.

**Comment by Vouivre** [comment]
I think it will be a good solution, thank you! I'll post my solution after adding some filters to the output of `kiss-outdated`.

**Comment by Vouivre** [comment]
Something like the following is enough at the moment

````
#!/bin/sh

kiss-outdated /var/db/kiss/repo-community/community  2>/dev/null | sed -n '/cups\|'\
'fdm\|'\
'msmtp\|'\
'youtube-dl/p'
````

I will add all my packages in this script. Later I will probably send the output to `herbe` to get a notification.

Thank you!
