### ISSUE TITLE
git: add post-install hook describing new behavior

### ISSUE THREAD

**Issue by echawk** [kiss-community/repo#61]
For the 2.35.2 release of git, there were some internal changes made to mitigate security vulnerabilties.[1]

For us this means that if someone has their kiss repositories owned by another user (let's say root), and they run `kiss u` the repositories will fail to sync.

For the time being, I have the following in `~/.gitconfig` to mitigate this problem:
```yaml
[safe]
        directory = *
```

Otherwise, when trying to access git repositories, you get the following error:
```shell
[ethan ~] % git -C /var/db/kiss/repos/repo/core rev-parse --show-superproject-working-tree 
fatal: unsafe repository ('/var/db/kiss/repos/repo' is owned by someone else) 
To add an exception for this directory, call: 
        git config --global --add safe.directory /var/db/kiss/repos/repo 
```

[1]  https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by ioraff** [comment]
If git already prints this message, I'm not sure this is necessary, especially since the install guide already recommends the repos be self-owned.

**Comment by echawk** [comment]
git prints this message, but kiss does not. Instead `kiss update` errors out silently. Fair point on the self owned git repository, but silent errors suck. Maybe it's worth adding a section to the README?

**Comment by deralmas** [comment]
@ehawkvu I think we should just fix kiss then.
