### ISSUE TITLE
linux-headers: not pinned to LTS

### ISSUE THREAD

**Issue by fluorescent-haze** [kiss-community/repo#65]
According to [Linux Kernel Documentation](https://www.kernel.org/doc/Documentation/kbuild/headers_install.txt):

> Kernel headers are backwards compatible, but not forwards compatible. This means that a program built against a C library using older kernel headers should run on a newer kernel (although it may not have access to new features), but a program built against newer kernel headers may not work on an older kernel.

Basically if you have linux-headers 5.17 installed (which is the current version in the repository) and have an LTS 5.15.x kernel (like myself), if you recompile libc and try compiling new programs, they might not work.

As [Dylan put it](https://kisslinux.org/wiki/pkg/kiss-linux):

> The kernel headers in KISS are pinned to an LTS kernel version and are only updated when there are changes of interest in the kernel or headers themselves.

As I'm not aware of a good reason to update the headers to the stable branch, I think It'd be a good idea to keep the linux headers at the latest LTS (currently 5.15.41), or the previous LTS (5.10.117), as they're recent enough to support most new features, but stable enough to not break anyone's system.

**Comment by ioraff** [comment]
My mistake. I had read conflicting information on backward vs forward compatibility, and just decided that a new stable release was a reasonable standard to follow. Resolved with 0681bf7.
