### ISSUE TITLE
proposal: Bring sed -i back?

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo#92]

**Comment by ioraff** [comment]
I'd rather ship a posix-compliant `ed` (i.e. one that supports regex, which busybox does not) and use that.

**Comment by illiliti** [comment]
It's impossible to use sed -i in portable way. Some implementations require extension argument, some don't, some don't implement this option at all.

See also: https://www.austingroupbugs.net/view.php?id=530

**Comment by aabacchus** [comment]
The current solution (`sed file >_; mv _ file`) works with every implementation, and doesn't require any new tools. There's no reason to stop using it. This is just for build scripts, it's ok to have one extra line for the sake of simplicity and portability.
