### ISSUE TITLE
proposal: DItch shithub

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo#94]
1. https://sr.ht
- Mailing list workflow
- ?

2. https://codeberg.org + External mailing list
- Both PR / mailing list workflow
- More familiar interface (issues, PRs, ...)
- ?

Mirrors should be maintained only for package repos

**Comment by ioraff** [comment]
sourcehut would be nice if and when they add orgs.

**Comment by aabacchus** [comment]
Orgs are missing, although I think you can currently allow other user accounts write access to individual repos. But if we go with a mailing-list workflow, who pushes commits from the mailing list to the canonical repo?

**Comment by illiliti** [comment]
nack on sourcehut. i don't want to get suddenly banned for dumb reason, which is why i will never have account there. plus, it does not support ipv6 at all. it's shame because even github has partial ipv6 support. and as has already been said, they don't have orgs.

IMHO having mailing lists there is OK, but no more.

**Comment by git-bruh** [comment]
So do we go ahead with it?

:+1: Codeberg
:smile: Sourcehut
:-1: Github

ML setup can be decided after this

**Comment by dilyn-corner** [comment]
Why not self-host :)

**Comment by git-bruh** [comment]
> Why not self-host :)

- uptime
- discoverability (relatively)
- (probably) won't be alive in 5 years' time

**Comment by jslick** [comment]
Can codeberg run "actions"?  I think there is a shellcheck task in repo-community.

**Comment by dilyn-corner** [comment]
Should we consider instead offloading the checks to the local user instead? We can distribute the check as a hook which git will run whenever the correct action takes place. If the check fails it could even probably stop the action. 

This way we don't have to worry about the infra supported by wherever we move.

> (probably) won't be alive in 5 years' time

oooofffff

**Comment by git-bruh** [comment]
> Can codeberg run "actions"? I think there is a shellcheck task in repo-community.

It has woodpecker CI but it's not openly available - you just have to ask them to grant you access https://codeberg.org/Codeberg-CI/request-access

**Comment by git-bruh** [comment]
https://codeberg.org/kiss-community/
